create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  steam_id64 text unique,
  role text default 'Carry',
  target_rank text default 'Legend',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  baseline text,
  target text,
  start_match_id bigint,
  status text default 'active',
  progress int default 0,
  created_at timestamptz default now(),
  completed_at timestamptz
);

alter table public.profiles enable row level security;
alter table public.missions enable row level security;

create policy "profiles own read" on public.profiles for select using (auth.uid()=id);
create policy "profiles own insert" on public.profiles for insert with check (auth.uid()=id);
create policy "profiles own update" on public.profiles for update using (auth.uid()=id) with check (auth.uid()=id);
create policy "missions own read" on public.missions for select using (auth.uid()=user_id);
create policy "missions own insert" on public.missions for insert with check (auth.uid()=user_id);
create policy "missions own update" on public.missions for update using (auth.uid()=user_id) with check (auth.uid()=user_id);
